name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 6a62c73e-62df-432d-b0e3-c59edfcd4410
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: e6fa68f2-0cca-46f4-a8e0-cb089f1bc4cb

      - name: 'Run az commands'
        run: |
          az storage blob download --account-name iamazurelab326857931 --container-name flag --name flag.txt --file - --auth-mode login | cat

